# Generated by Django 3.0.8 on 2020-07-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trainlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_date', models.IntegerField()),
                ('category', models.CharField(choices=[('chest', '胸'), ('shoulder', '肩'), ('spine', '背中'), ('arm', '腕'), ('abs', '腹'), ('leg', '脚')], max_length=100)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
