# Generated by Django 3.0.8 on 2020-07-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscle', '0002_auto_20200723_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainlog',
            name='comment',
            field=models.CharField(max_length=100),
        ),
    ]
