# Generated by Django 3.0.8 on 2020-07-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscle', '0003_auto_20200723_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_date', models.DateField(verbose_name='日付')),
                ('weight', models.FloatField()),
            ],
        ),
    ]
