# Generated by Django 3.0.8 on 2020-07-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscle', '0004_bodyweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyweight',
            name='weight',
            field=models.FloatField(max_length=10),
        ),
    ]
